### ISSUE TITLE
Forgotten code in `state.py`

### ISSUE THREAD

**Issue by PhilippMatthes** [urbanAIthi/GLOSA_RL#1]
Hey, I saw your paper at ITSC. First of all, thank you for being transparent and making your code public. Not many GLOSA studies have posted their code online, so this is definitely very valuable. To me, it helps to understand the assumptions of simulation environments for GLOSA to further assess your approach's practicality for our real-world application (https://github.com/priobike)

Anyway, I found this dead/forgotten code that you may want to fix:

https://github.com/urbanAIthi/GLOSA_RL/blob/7e3cab7c21d60f7afa2251d9334a8a5fbe615efd/GLOSA_gym/state.py#L196

**Comment by urbanAIthi** [comment]
Hi,
thank you for your interest in our research. 
Also thanks for pointing out the issue, we fixed the issue. 

BR, 
Jeremias
